// Generated by Upstream/sync_upstream.py — do not edit.
// Lets Upstream/index.html open directly from disk (file://),
// where the browser blocks fetch('data.json').
window.UPSTREAM_DATA = [
  {
    "date": "Jul 23, 2026",
    "ts": "2026-07-23T13:00:15Z",
    "sha": "390729a8007a9c09be38416bc7755e4fa04165c3",
    "commit": "bump handy keys 0.3.2",
    "status": "Pending",
    "notes": "",
    "pr": ""
  },
  {
    "date": "Jul 22, 2026",
    "commit": "fix mute bug (#1760)",
    "status": "Pending",
    "notes": "",
    "pr": "1760",
    "sha": "8a362e9eba59d4057fda79b7f38f5b0d5cbabf65",
    "ts": "2026-07-22T09:03:01Z"
  },
  {
    "date": "Jul 22, 2026",
    "commit": "fix: place Windows overlay on secondary monitors (#1733)",
    "status": "Pending",
    "notes": "",
    "pr": "1733",
    "sha": "e1152d86935562264d7c5637d77ce2e29aeef57e",
    "ts": "2026-07-22T07:52:15Z"
  },
  {
    "date": "Jul 21, 2026",
    "commit": "update catalog",
    "status": "Pending",
    "notes": "",
    "pr": "",
    "sha": "e8c73ba700378c7275b9bbf951f3be2e1257c309",
    "ts": "2026-07-21T12:32:23Z"
  },
  {
    "date": "Jul 21, 2026",
    "commit": "fix: restore clipboard images after paste (#1231)",
    "status": "Pending",
    "notes": "",
    "pr": "1231",
    "sha": "3ed2b2190fc56a998a1a3c2c95b133c2531660e7",
    "ts": "2026-07-21T11:39:46Z"
  },
  {
    "date": "Jul 21, 2026",
    "commit": "Add Danish translations (#1747)",
    "status": "Merged",
    "notes": "Clean cherry-pick. Danish translation file taken verbatim; languages.ts updated with da entry at priority 24.",
    "pr": "1747",
    "sha": "f4e3587bac44eead5896bb8809076e4ce59caf00",
    "ts": "2026-07-21T11:22:58Z"
  },
  {
    "date": "Jul 21, 2026",
    "commit": "feat: windows single left click on tray icon opens handy window (#369)",
    "status": "Pending",
    "notes": "",
    "pr": "369",
    "sha": "b462aa390f3c7af7b9ed2d3a935ed0f429c30286",
    "ts": "2026-07-21T10:34:27Z"
  },
  {
    "date": "Jul 21, 2026",
    "commit": "Refactor Sidebar settings structure (#1720)",
    "status": "Ignored",
    "notes": "Grain has custom sidebar structure with additional tabs (Speech to Text, Grain Space, Experimentations). Applied custom ordering instead.",
    "pr": "1720",
    "sha": "cdf5028b5a8f2e66bf41d2fc5401c313d6900d16",
    "ts": "2026-07-21T08:52:54Z"
  },
  {
    "date": "Jul 21, 2026",
    "commit": "release v0.9.4",
    "status": "Ignored",
    "notes": "Upstream version bump; Grain versions independently",
    "pr": "",
    "sha": "17d6c763413e3e29ec5cee76aa19ad01eccb73b2",
    "ts": "2026-07-21T04:47:15Z"
  },
  {
    "date": "Jul 21, 2026",
    "commit": "dont use hf env",
    "status": "Pending",
    "notes": "",
    "pr": "",
    "sha": "68af495ea6fbe129e8bb23b335a76a21a43765b9",
    "ts": "2026-07-21T04:39:48Z"
  },
  {
    "date": "Jul 21, 2026",
    "commit": "guard vulkan so only available to true x86 host, not emulated (#1731)",
    "status": "Pending",
    "notes": "",
    "pr": "1731",
    "sha": "46d6a2aec85560b1a5f627a17423d2f0dbf94960",
    "ts": "2026-07-21T04:29:58Z"
  },
  {
    "date": "Jul 21, 2026",
    "commit": "fix windows not shutting down cleanly because of handy (#1732)",
    "status": "Pending",
    "notes": "",
    "pr": "1732",
    "sha": "0470d9ad1745ae25af6b50d4cad9affd0d1acc65",
    "ts": "2026-07-21T00:35:07Z"
  },
  {
    "date": "Jul 20, 2026",
    "commit": "bump tauri global shortcut package.json",
    "status": "Pending",
    "notes": "",
    "pr": "",
    "sha": "59ec6959b8649afd9f9562fdb6ce25e911e1dd08",
    "ts": "2026-07-20T12:49:39Z"
  },
  {
    "date": "Jul 20, 2026",
    "commit": "bump tauri global shortcut",
    "status": "Pending",
    "notes": "",
    "pr": "",
    "sha": "2281b8b2dfaa56a29e208b9207c04c1f155455b0",
    "ts": "2026-07-20T12:42:06Z"
  },
  {
    "date": "Jul 20, 2026",
    "commit": "bump to handy-keys 0.3.1",
    "status": "Pending",
    "notes": "",
    "pr": "",
    "sha": "468129fdf1f7b1b8275f4b40c572f28b91d7f701",
    "ts": "2026-07-20T12:10:48Z"
  },
  {
    "date": "Jul 20, 2026",
    "commit": "fix(linux): install app-private libs to /usr/lib/Handy (#1639) (#1727)",
    "status": "Pending",
    "notes": "",
    "pr": "1639",
    "sha": "d1180c42ceb344c8219ac419ba6a71c7c938d15c",
    "ts": "2026-07-20T09:21:28Z"
  },
  {
    "date": "Jul 20, 2026",
    "commit": "fix update checker overlay",
    "status": "Pending",
    "notes": "",
    "pr": "",
    "sha": "86616891af0f1ba43620f4f9601593a38e71f320",
    "ts": "2026-07-20T07:48:59Z"
  },
  {
    "date": "Jul 20, 2026",
    "commit": "fix: prevent custom-word correction from losing transcriptions",
    "status": "Pending",
    "notes": "",
    "pr": "",
    "sha": "2203a826c62a83022fc40d0ea6314d218c73f9c0",
    "ts": "2026-07-20T06:58:29Z"
  },
  {
    "date": "Jul 18, 2026",
    "commit": "Add missing translations (#1709)",
    "status": "Merged",
    "notes": "it: 3 keys translated (capabilities.languageCount, modelUnload.title, clamshellMicrophone.title) \u2014 clean apply. de/fr: all 5 hunks targeted upstream-only keys Grain already removed (existingModelsTitle/showAllModels/showFewerModels, selectModel, languageCount, overlay.style/position, voiceActivityDetection) \u2192 conflicts resolved by keeping Grain HEAD; de/fr unchanged (nothing to translate).",
    "pr": "1709",
    "sha": "cdbc22390987643237756382ef367f7244b2844f",
    "ts": "2026-07-18T09:41:24Z"
  },
  {
    "date": "Jul 18, 2026",
    "commit": "drop 'direct' paste method from the ui for macOS (#1708)",
    "status": "Merged",
    "notes": "Clean cherry-pick. Grain PasteMethod.tsx matched upstream pre-fix structure; Grain Dropdown already supported DropdownOption.disabled, so the macOS hide-but-keep-manual-selection logic works as-is.",
    "pr": "1708",
    "sha": "3cbbe58272e2067b05645f42a65b7b79b36a83dc",
    "ts": "2026-07-18T07:57:54Z"
  },
  {
    "date": "Jul 17, 2026",
    "commit": "feat: add Hindi (hi) translation (#1701)",
    "status": "Merged",
    "notes": "Clean cherry-pick. New file taken verbatim per Grain precedent (cf. ne): upstream-only keys (whatsNew, selectModel, languageCount, overlay.style, ggml, voiceActivityDetection) sit unused; Grain-only sections (agent, grainSpace, grainSpaceOverlay, experimentations.snippets, settings.speechToText cloud) fall back to en at runtime. languages.ts hi entry added at priority 23.",
    "pr": "1701",
    "sha": "d861e24bc825c699ccf7215a430684c6e322131c",
    "ts": "2026-07-16T23:42:11Z"
  },
  {
    "date": "Jul 17, 2026",
    "commit": "chore(i18n): update and correct Spanish translation (#1697)",
    "status": "Merged",
    "notes": "Conflict reconciled against Grain en structure: kept Grain-only keys (loadModels/downloadModel, multiLanguage, acceleration.whisper, flat overlay, translateToEnglish.descriptionUnsupported, acknowledgments.whisper, footer downloadUpdate/restart), skipped upstream-only keys absent from en (existingModelsTitle/showAllModels/showFewerModels, languageCount, selectModel, voiceActivityDetection, ggml ack, overlay.style/position split), took upstream's sentence-case Spanish corrections + liveLogs block (present in Grain en).",
    "pr": "1697",
    "sha": "bd8e549a742eaf9c1f54a6bf111bc53929375320",
    "ts": "2026-07-16T23:40:08Z"
  },
  {
    "date": "Jul 15, 2026",
    "commit": "release v0.9.3",
    "status": "Ignored",
    "notes": "Upstream version bump; Grain versions independently",
    "pr": "",
    "sha": "b9925d01972a933544d0344a2e62360580368f18",
    "ts": "2026-07-15T12:48:04Z"
  },
  {
    "date": "Jul 15, 2026",
    "commit": "fix(model-card): prevent reselection of currently active model (#1662)",
    "status": "Merged",
    "notes": "Clean cherry-pick",
    "pr": "1662",
    "sha": "497653014c3293be09adc082305c14e6abdfa3f0",
    "ts": "2026-07-15T12:44:37Z"
  },
  {
    "date": "Jul 15, 2026",
    "commit": "fix: prevent history audio players from playing simultaneously (#1665)",
    "status": "Merged",
    "notes": "AudioPlayerGroup wrapper; kept Grain list markup and copyText prop",
    "pr": "1665",
    "sha": "4be7911d4de7935eeb2a6b817dc4b506ed7ca911",
    "ts": "2026-07-15T09:03:23Z"
  },
  {
    "date": "Jul 15, 2026",
    "commit": "Declutter model cards (only show quantization label on modelcard in debug mode) (#1685)",
    "status": "Ignored",
    "notes": "Grain's ModelCard shows no quant label at all",
    "pr": "1685",
    "sha": "4357c728d9670381b1acabb6a92d937ceb629ad3",
    "ts": "2026-07-15T08:58:01Z"
  },
  {
    "date": "Jul 15, 2026",
    "commit": "bump tauri version and Mac dock fixes (#1675)",
    "status": "Merged",
    "notes": "tauri 2.11.5 + api/cli ^2.11; cjpais runtime fork replaced by tao rev pin; overlay Dock fix n/a (native pill)",
    "pr": "1675",
    "sha": "5a7c0eac1ac250142b9fe58a898cbf79cf9f1814",
    "ts": "2026-07-15T07:14:58Z"
  },
  {
    "date": "Jul 15, 2026",
    "commit": "fix(models): handle Hugging Face linked size headers (#1678)",
    "status": "Merged",
    "notes": "hf-hub fork pin bumped 63b6034->9918f11",
    "pr": "1678",
    "sha": "b00ae666c57e972b2d3494fc76d8166ffa59032e",
    "ts": "2026-07-15T06:44:24Z"
  },
  {
    "date": "Jul 12, 2026",
    "commit": "release v0.9.2",
    "status": "Ignored",
    "notes": "Upstream version bump; Grain versions independently",
    "pr": "",
    "sha": "ea10f7454e86f893581f5a380a15866476aa6423",
    "ts": "2026-07-12T12:20:46Z"
  },
  {
    "date": "Jul 12, 2026",
    "commit": "transcribe 0.1.3 (#1664)",
    "status": "Merged",
    "notes": "Bumped transcribe-cpp version.",
    "pr": "1664",
    "sha": "c912c6baaeef20b11e5744feedffc57cab3ab69b",
    "ts": "2026-07-12T04:54:27Z"
  },
  {
    "date": "Jul 11, 2026",
    "commit": "Add cancel download functionality to Onboarding component (#1653)",
    "status": "Merged",
    "notes": "Adapted to Grain flat onboarding layout; store/ModelCard infra already present",
    "pr": "1653",
    "sha": "38825767cf933f59b90209c3f3c5f1e3bbe98766",
    "ts": "2026-07-11T03:04:15Z"
  },
  {
    "date": "Jul 11, 2026",
    "commit": "Update descriptions for Moonshine models (#1648)",
    "status": "Merged",
    "notes": "AUDIT 2026-07-17: was NOT actually applied - all 12 Moonshine models still read \"English speech-to-text\". Fixed by taking upstream catalog.json verbatim (also converged its hand-reformatting).",
    "pr": "1648",
    "sha": "8c46721a77cf157092802f1024c04394b22d1113",
    "ts": "2026-07-11T00:31:15Z"
  },
  {
    "date": "Jul 10, 2026",
    "commit": "release v0.9.1",
    "status": "Merged",
    "notes": "Bumped version to 0.9.1 in Cargo.toml, tauri.conf.json, and package.json.",
    "pr": "",
    "sha": "1c4f21acd2bab81f75a0cd7556cd3bb7399ffd9a",
    "ts": "2026-07-10T12:24:05Z"
  },
  {
    "date": "Jul 10, 2026",
    "commit": "feat: add Light / Dark / System appearance selector (#1599)",
    "status": "Ignored",
    "notes": "Ignored. Grain has a highly custom, split-theme architecture via ThemeContext.tsx (allowing dark Quick Panel with light Settings). Upstream's implementation is a global document.documentElement override, which is incompatible with Grain's per-panel toggles.",
    "pr": "1599",
    "sha": "d929a9468aad8cfecf5b175c4383cea942fe5399",
    "ts": "2026-07-10T10:58:17Z"
  },
  {
    "date": "Jul 10, 2026",
    "commit": "Merge branch 'main' of github.com:cjpais/Handy",
    "status": "Merged",
    "notes": "Upstream branch merge. No code to port.",
    "pr": "",
    "sha": "d1bc82a0ee5be3ab0e84c834c472ee559847c627",
    "ts": "2026-07-10T09:09:12Z"
  },
  {
    "date": "Jul 10, 2026",
    "commit": "update windows build instruction",
    "status": "Merged",
    "notes": "Added Windows prerequisites, MAX_PATH fixes, and code-signing bypass instructions to BUILD.md.",
    "pr": "",
    "sha": "158168983cfcf01c4555e012a62a7b1ccad77bd4",
    "ts": "2026-07-10T09:08:52Z"
  },
  {
    "date": "Jul 10, 2026",
    "commit": "fix: surface download errors during onboarding (#1522)",
    "status": "Merged",
    "notes": "Hoisted the sonner Toaster in AppInner so that model download errors are visible during onboarding.",
    "pr": "1522",
    "sha": "1fd3f912e2ea950d1694c68199b6e215926b1c81",
    "ts": "2026-07-10T08:57:32Z"
  },
  {
    "date": "Jul 10, 2026",
    "commit": "fix: push-to-talk rapidly toggles recording under X11 auto-repeat (defer synthesized releases) (#1605)",
    "status": "Merged",
    "notes": "Deferral gate auto-threaded ahead of Grain debounce/send-to-AI; 7 new tests pass",
    "pr": "1605",
    "sha": "438582fc64321a8a17838db6703079ccdcc15982",
    "ts": "2026-07-10T08:13:32Z"
  },
  {
    "date": "Jul 09, 2026",
    "commit": "fix: tray icon invisible on Windows with dark taskbar + light apps (#1423) (#1636)",
    "status": "Ignored",
    "notes": "Grain uses a single branded tray icon by design",
    "pr": "1423",
    "sha": "bf258d10fbdb15cac57e5d26318228ae01641fc1",
    "ts": "2026-07-09T10:19:59Z"
  },
  {
    "date": "Jul 09, 2026",
    "commit": "fix: cancel stalled output processing (#1614)",
    "status": "Merged",
    "notes": "Added the cancel-generation infra Grain lacked; cancel now aborts in-flight LLM/paste",
    "pr": "1614",
    "sha": "f79a907fc0d3a1ef689bc338de35ab0bcab68029",
    "ts": "2026-07-09T09:20:41Z"
  },
  {
    "date": "Jul 09, 2026",
    "commit": "fix(tray): log tray icon failures instead of panicking (#1355)",
    "status": "Merged",
    "notes": "Safely merged into `tray.rs`",
    "pr": "1355",
    "sha": "2dd35bbb5a85a0fa46f539a0c2a06d1a246c88fa",
    "ts": "2026-07-09T09:02:20Z"
  },
  {
    "date": "Jul 09, 2026",
    "commit": "[bugfix] keep track of current tray icon state (#1158)",
    "status": "Merged",
    "notes": "Kept Grain non-panicking icon load; menu now reflects real state",
    "pr": "1158",
    "sha": "5464bfaa0826ec367a052514d87575f92e0113fc",
    "ts": "2026-07-09T08:52:42Z"
  },
  {
    "date": "Jul 08, 2026",
    "commit": "bump version (#1634)",
    "status": "Merged",
    "notes": "Bumped `transcribe-cpp` to 0.1.2.",
    "pr": "1634",
    "sha": "87c45f814be4b7e7ee9b0783c1fe74e2c74d99c6",
    "ts": "2026-07-08T13:51:08Z"
  },
  {
    "date": "Jul 08, 2026",
    "commit": "Apply paste delay after key press and increase slider range (#1465)",
    "status": "Merged",
    "notes": "Added dual paste delays (before/after), bumped slider to 500ms, and updated translations.",
    "pr": "1465",
    "sha": "f0f7e7ff4674eb0d4fceb4da49f75934555f55b4",
    "ts": "2026-07-08T09:48:10Z"
  },
  {
    "date": "Jul 08, 2026",
    "commit": "logging",
    "status": "Merged",
    "notes": "",
    "pr": "",
    "sha": "07637ea932bcc9d9813f2f6caa7c766b89a513f6",
    "ts": "2026-07-08T09:28:10Z"
  },
  {
    "date": "Jul 07, 2026",
    "commit": "fix: add prompt injection defense to default post-processing prompt (#1261) (#1310)",
    "status": "Ignored",
    "notes": "Irrelevant (Grain manages its own custom prompts).",
    "pr": "1310",
    "sha": "fc465b49f0522ca359b36a784a325db8521dfb1c",
    "ts": "2026-07-08T09:25:35Z"
  },
  {
    "date": "Jul 08, 2026",
    "commit": "fix: prevent abort on quit by handling poisoned mutexes in Drop impls (#1354)",
    "status": "Merged",
    "notes": "Recover poisoned mutexes inside Drop impls using `match` + logged warnings.",
    "pr": "1354",
    "sha": "a6df742880ada3c006ad376c1a89d8565b003e69",
    "ts": "2026-07-08T09:24:18Z"
  },
  {
    "date": "Jul 08, 2026",
    "commit": "fix: reset resampler state between recordings to prevent audio crosstalk (#1344)",
    "status": "Merged",
    "notes": "Added `reset()` to `FrameResampler` on `Cmd::Start`.",
    "pr": "1344",
    "sha": "eb9301e01c8f53383eea5d5252035c4aabe75bc3",
    "ts": "2026-07-08T09:11:47Z"
  },
  {
    "date": "Jul 08, 2026",
    "commit": "fix build",
    "status": "Ignored",
    "notes": "n/a - Grain kept its own bindings.ts typings, no optional bindings",
    "pr": "",
    "sha": "11c2bb1eb8eab5b0472e03d49a908a60010d8777",
    "ts": "2026-07-08T09:11:42Z"
  },
  {
    "date": "Jul 08, 2026",
    "commit": "fix: throttle mic-level IPC to mitigate WebKitWebProcess memory leak (#1444)",
    "status": "Merged",
    "notes": "Throttled `emit_levels` to 30 FPS in `overlay.rs`.",
    "pr": "1444",
    "sha": "e2c72a25ff48f280729e9e9bac289802c2c01cfd",
    "ts": "2026-07-08T09:03:50Z"
  },
  {
    "date": "Jul 08, 2026",
    "commit": "handy keys 0.3.0 (#1623)",
    "status": "Merged",
    "notes": "Bumped in `Cargo.toml`.",
    "pr": "1623",
    "sha": "a201be9161cd3e62934dec98531204beb1a2a062",
    "ts": "2026-07-08T08:23:13Z"
  },
  {
    "date": "Jul 08, 2026",
    "commit": "Add Nepali translation (#1632)",
    "status": "Merged",
    "notes": "Added `ne` translation.",
    "pr": "1632",
    "sha": "58760b22cd13e709384a617a6d86b7df506a65ae",
    "ts": "2026-07-08T08:19:02Z"
  },
  {
    "date": "Jul 08, 2026",
    "commit": "fix(build): auto-fall-back to AI stub on Command Line Tools-only macOS (#1510)",
    "status": "Merged",
    "notes": "Added CLT fallback logic in `build.rs`.",
    "pr": "1510",
    "sha": "485f4ade00169fd8a620c17d1478ad198252e953",
    "ts": "2026-07-08T08:11:02Z"
  },
  {
    "date": "Jul 08, 2026",
    "commit": "salvage valid settings instead of resetting store on parse failure (#1631)",
    "status": "Merged",
    "notes": "Reimplemented in grain-core AppContext (headless store); secrets file protected; +4 tests",
    "pr": "1631",
    "sha": "cd040d9324079d952a0457d0e1a7e0c05af70e44",
    "ts": "2026-07-08T08:01:55Z"
  },
  {
    "date": "Jul 08, 2026",
    "commit": "add openblas to ci and packaging for linux (#1621)",
    "status": "Merged",
    "notes": "Added OpenBLAS checks to Linux CI/packaging.",
    "pr": "1621",
    "sha": "66e57ca865778dfdeb78bf1a4e69a0accc399ca1",
    "ts": "2026-07-07T23:56:51Z"
  },
  {
    "date": "Jul 07, 2026",
    "commit": "fix: preserve ampersands in custom words (#1569)",
    "status": "Merged",
    "notes": "Clean cherry-pick",
    "pr": "1569",
    "sha": "0a59e1f3001c64dc4afc955f376508b1a11061c0",
    "ts": "2026-07-07T11:12:22Z"
  },
  {
    "date": "Jul 07, 2026",
    "commit": "fix: preserve active overlay during post-processing (#1597)",
    "status": "Ignored",
    "notes": "Irrelevant (Grain uses a native Rust pill architecture).",
    "pr": "1597",
    "sha": "cdb46339cd2dcd82f5a82aeed0b759096c66fb0b",
    "ts": "2026-07-07T10:57:48Z"
  },
  {
    "date": "Jul 07, 2026",
    "commit": "Update Italian translations (#1604)",
    "status": "Merged",
    "notes": "Updated `it` translations.",
    "pr": "1604",
    "sha": "45e3eed8df242339453cda16888376d6305c06b5",
    "ts": "2026-07-07T10:51:44Z"
  },
  {
    "date": "Jul 06, 2026",
    "commit": "Fix GigaAM v3 description. (#1613)",
    "status": "Merged",
    "notes": "Corrected descriptions to \"Russian speech-to-text\".",
    "pr": "1613",
    "sha": "dad37baa0315c63c3a3d91af1fdcd6ad6e401f4f",
    "ts": "2026-07-06T14:44:36Z"
  },
  {
    "date": "Jul 05, 2026",
    "commit": "fix: gate whisper run extension on model arch, not Feature::InitialPrompt (#1603)",
    "status": "Merged",
    "notes": "AUDIT 2026-07-17: was HALF-applied - run-extension gate was correct but the fuzzy-correction gate still used Feature::InitialPrompt, so custom words were silently dropped for non-whisper models advertising it. Fixed, and the same root cause fixed in the Grain-only rolling path (upstream fix could not reach it).",
    "pr": "1603",
    "sha": "f96a7afb285c900879a2863ccce76d14e1a07fed",
    "ts": "2026-07-05T07:13:28Z"
  },
  {
    "date": "Jul 05, 2026",
    "commit": "move to auto timestamps for all models (#1602)",
    "status": "Merged",
    "notes": "Batch path only; rolling keeps Word timestamps + coarse fallback",
    "pr": "1602",
    "sha": "afbe763dcac5a2c14d5c6d1b8215639a563ffbef",
    "ts": "2026-07-05T05:50:55Z"
  },
  {
    "date": "Jul 04, 2026",
    "commit": "Improve Dutch (nl) translation accuracy and consistency (#1594)",
    "status": "Merged",
    "notes": "Improved `nl` translations.",
    "pr": "1594",
    "sha": "6d92e2cc6902c18d8d3362872fda889172bdb261",
    "ts": "2026-07-04T07:05:42Z"
  },
  {
    "date": "Jul 04, 2026",
    "commit": "Update Japanese translations (#1593)",
    "status": "Merged",
    "notes": "Fixed encoding and translated English strings in `ja`.",
    "pr": "1593",
    "sha": "99ac7ebb23473d8ce5b63e6578f37e239b89e738",
    "ts": "2026-07-04T07:05:25Z"
  },
  {
    "date": "Jul 04, 2026",
    "commit": "Add Dutch (Nederlands) translation (#1590)",
    "status": "Merged",
    "notes": "Added `nl` translation.",
    "pr": "1590",
    "sha": "3f49cf100b33f7a164662cf3f1b953207ab37c7b",
    "ts": "2026-07-03T23:12:04Z"
  },
  {
    "date": "Jul 03, 2026",
    "commit": "bump to transcribe-cpp-0.1.1 (#1589)",
    "status": "Merged",
    "notes": "Bumped transcribe-cpp to 0.1.1.",
    "pr": "1589",
    "sha": "5f54e17cfca5fd8fd5c61b3dd8aeb37ae45edbbc",
    "ts": "2026-07-03T13:56:17Z"
  },
  {
    "date": "Jul 03, 2026",
    "commit": "fix cyrillic (unicode) path problems (#1187)",
    "status": "Merged",
    "notes": "Fixed VAD crash on Cyrillic paths.",
    "pr": "1187",
    "sha": "c06cce72f61ef1eb8b3565121825a5d57a72033a",
    "ts": "2026-07-03T06:27:47Z"
  },
  {
    "date": "Jul 03, 2026",
    "commit": "faster mic initialization (#1582)",
    "status": "Merged",
    "notes": "Adapted: config/device caches + first-buffer fix rewoven around pill/rolling/conditioning; overlay part n/a (native pill)",
    "pr": "1582",
    "sha": "cb9654ca88744606452e6ef856296eb409819950",
    "ts": "2026-07-03T04:48:30Z"
  },
  {
    "date": "Jul 02, 2026",
    "commit": "ship vsredist directly with the app (#1577)",
    "status": "Merged",
    "notes": "build.rs staging cherry-picked; redist locator wired into grain-release.yml (x64) instead of upstream build.yml",
    "pr": "1577",
    "sha": "f13597061ad36b1a4430d61a48aa15a5d4b96e14",
    "ts": "2026-07-02T12:18:59Z"
  },
  {
    "date": "Jul 01, 2026",
    "commit": "edit model recs",
    "status": "Merged",
    "notes": "Skipped (Grain manages custom catalog).",
    "pr": "",
    "sha": "9b0d8a1120810dac1b139f480d37ba5f704e4856",
    "ts": "2026-07-01T13:31:55Z"
  },
  {
    "date": "Jul 01, 2026",
    "commit": "update language selector",
    "status": "Merged",
    "notes": "Ported language selector improvements.",
    "pr": "",
    "sha": "dc01346d1cf2ca44b2c726b7140c93dbf929c086",
    "ts": "2026-07-01T13:22:49Z"
  },
  {
    "date": "Jul 01, 2026",
    "ts": "2026-07-01T12:38:20Z",
    "sha": "31d8fc2442c2412d6e9de6e018cf70edfbc37ca5",
    "commit": "introduce transcribe.cpp (#1529)",
    "status": "Merged",
    "notes": "Absorbed by an upstream merge (in our ancestry).",
    "pr": "1529"
  },
  {
    "date": "Jun 25, 2026",
    "commit": "debug + perf transcribe cli (#1541)",
    "status": "Merged",
    "notes": "Ported live log viewer and perf cli.",
    "pr": "1541",
    "sha": "bff4db7e757125b00ca5d93afacb902c19e3eb8c",
    "ts": "2026-06-25T05:11:45Z"
  },
  {
    "date": "Jun 24, 2026",
    "commit": "fix: stop overlay mic-level events leaking memory when overlay disabled (#1447)",
    "status": "Merged",
    "notes": "Fixed Tauri memory leak from overlay.",
    "pr": "1447",
    "sha": "a92a4d5e497bc1d7bc8d228c77636c4e600453a9",
    "ts": "2026-06-24T00:49:30Z"
  },
  {
    "date": "Jun 24, 2026",
    "commit": "fix: skip post-processing when transcription is empty (#1537)",
    "status": "Merged",
    "notes": "Applied upstream check.",
    "pr": "1537",
    "sha": "c8eb33bc59bd6e1a3959c40c4b435c6e18d633bf",
    "ts": "2026-06-24T00:13:31Z"
  },
  {
    "date": "Jun 23, 2026",
    "commit": "Clarified branding and redistribution terms for Handy",
    "status": "Ignored",
    "notes": "Irrelevant (Grain is an independent fork).",
    "pr": "",
    "sha": "8f72266842d759af385f812fc093ea829fbdf9f1",
    "ts": "2026-06-23T14:32:21Z"
  },
  {
    "date": "Jun 23, 2026",
    "commit": "live debug log viewer in app (#1535)",
    "status": "Merged",
    "notes": "AUDIT 2026-07-17: startup WEBVIEW_LOG_STREAMING.store was missing, so the live log viewer was empty until debug mode was toggled. Fixed.",
    "pr": "1535",
    "sha": "e526733f09844c150bdaa0889ff9b9e456cc30dc",
    "ts": "2026-06-23T13:05:49Z"
  },
  {
    "date": "Jun 18, 2026",
    "commit": "fix: dropdown overflow in post-processing settings (#1402)",
    "status": "Merged",
    "notes": "Ported silently during Dark Mode / UI overhaul. Grain's `Dropdown` already uses the identical grid fix.",
    "pr": "1402",
    "sha": "bc6a41e418dda66a1f8d0b123e6a83880a66b6a1",
    "ts": "2026-06-18T01:54:13Z"
  },
  {
    "date": "Jun 11, 2026",
    "commit": "fix(models): show size for downloaded models (#1484)",
    "status": "Merged",
    "notes": "Model sizes already visible in Grain UI with dynamic icons (ported during UI overhaul).",
    "pr": "1484",
    "sha": "cfab1dda9db103e95e9fe2f4d76d2168caf0a59d",
    "ts": "2026-06-11T00:58:14Z"
  },
  {
    "date": "Jun 11, 2026",
    "commit": "fix(visualizer): scale FFT window to device sample rate (#1491)",
    "status": "Merged",
    "notes": "FFT scaling already present in `recorder.rs` (likely ported during audio perf rewrite).",
    "pr": "1491",
    "sha": "dd6cc676112b9c8123ebd34c6765444b7a855cfb",
    "ts": "2026-06-11T00:50:36Z"
  }
];
window.UPSTREAM_STATUS = {
  "upstream_head": "390729a8",
  "upstream_subject": "bump handy keys 0.3.2",
  "upstream_date": "2026-07-23T21:00:15+08:00",
  "latest_tag": "v0.9.4",
  "merge_base": "cdbc2239",
  "behind": 18,
  "trial_clean": false,
  "conflicts": [
    ".nix/bun-lock-hash",
    "package.json",
    "scripts/gen_catalog.py",
    "src-tauri/Cargo.toml",
    "src-tauri/src/handy/managers/transcription.rs",
    "src/components/Sidebar.tsx",
    "src/components/settings/AccelerationSelector.tsx",
    "src/i18n/locales/da/translation.json"
  ],
  "drift": [],
  "checked_at": "2026-07-23T18:54:30Z"
};
