//! [GRAIN] The installed-application catalogue — what the app picker offers.
//!
//! # Why the Shell's Applications folder, and not an installed-software list
//!
//! The question a picker has to answer is "what can this user launch?", not
//! "what is installed?". Those are different lists, and the registry's uninstall
//! keys answer the second one: runtimes, redistributables, SDKs, drivers and
//! update components, most of which are not applications anybody dictates into.
//!
//! Windows already maintains the first list — the Shell's `AppsFolder`, which is
//! what the Start menu is a view of. It is the union of desktop apps that placed
//! a Start entry and every packaged (MSIX / Store) app, which is exactly the set
//! a person would think to name.
//!
//! # What an entry has to carry
//!
//! An app in a context profile is only useful if it can be recognised again when
//! it is in the foreground, and detection sees two things: the process's
//! executable, and — for packaged apps — its AppUserModelID. So every row here
//! resolves to one of those two, or it is dropped. A picker offering an app that
//! could never match would be worse than not offering it.
//!
//! Both come off the shell item as properties:
//!
//! - `System.Link.TargetParsingPath` is the real executable, and it is present
//!   even when the entry's own identity is opaque — Chrome's is the bare string
//!   `Chrome`, Zen's is `F0DC299D809B9700`, and a shortcut with arguments gets a
//!   generated `Microsoft.AutoGenerated.{GUID}`. All three still name their exe
//!   here, which is why this property (rather than the entry's parsing name) is
//!   what the catalogue is built on.
//! - `System.AppUserModel.ID` is the identity, and for a packaged app it is the
//!   *only* one — those entries have no target path at all, because there is no
//!   shortcut behind them. It is also byte-for-byte what `GetApplicationUserModelId`
//!   reports for a running packaged process, which is what makes the match work.
//!
//! Measured against a real machine's 214 entries: 120 desktop apps, 41 packaged,
//! 53 non-applications (documentation, readmes, web links), and zero that could
//! not be classified.
//!
//! # What is deliberately NOT filtered
//!
//! Only entries that cannot be an application at all. The Start menu carries a
//! fair amount of documentation and a few uninstallers, and those are dropped —
//! but nothing else is, because the costs are lopsided: an odd extra row in a
//! list you search by typing is nearly free, while an app wrongly filtered out
//! makes the feature simply not work for whoever needed it.

use serde::{Deserialize, Serialize};
use specta::Type;

/// One launchable application.
#[derive(Serialize, Deserialize, Debug, Clone, Type, PartialEq, Eq)]
pub struct InstalledApp {
    /// What the Start menu calls it.
    pub name: String,
    /// The identity a context profile stores: a lowercased executable stem for a
    /// desktop app (`code`), an AppUserModelID for a packaged one
    /// (`Claude_pzs8sxrjxfjjc!Claude`). Matched against the foreground window.
    pub target: String,
    /// What to ask the Shell for a picture of: the executable's full path, or
    /// the AppUserModelID. Distinct from `target` because matching wants the
    /// least-specific form (a stem, so an app that moves still matches) and
    /// icons want the most specific one.
    pub icon_id: String,
}

/// Every application this user can launch, sorted by name.
///
/// Slow enough (a Shell namespace walk plus two property reads per entry) that
/// callers must be off any path a user is waiting on. Empty on failure and on
/// platforms without an implementation — the picker then falls back to typing a
/// name, which is what it did before this existed.
pub fn installed_apps() -> Vec<InstalledApp> {
    #[cfg(windows)]
    {
        windows_impl::enumerate()
    }
    #[cfg(not(windows))]
    {
        // macOS: `/Applications` + `NSWorkspace` bundle identifiers.
        // Linux: XDG desktop entries (`Exec=` gives the binary directly).
        // Both produce the same two-field identity and slot in here.
        Vec::new()
    }
}

/// Whether an executable stem is machinery rather than an application.
///
/// The bulk of the list is Microsoft's own documented set of executables that
/// Windows itself refuses to pin or to show in the Start menu's frequent list
/// (see "Exclusion Lists for Taskbar Pinning" in the AppUserModelIDs docs) —
/// worth borrowing rather than re-deriving, since it encodes which binaries the
/// shell considers not-an-app.
///
/// The uninstaller shapes are ours: a Start menu reliably carries "Uninstall X"
/// entries, and those are the one kind of junk a user might actually click by
/// mistake while looking for X itself.
fn is_not_an_app(stem: &str) -> bool {
    const NEVER: &[&str] = &[
        // Installers and uninstallers.
        "setup",
        "install",
        "isuninst",
        "unwise",
        "unwise32",
        "st5unst",
        "msiexec",
        "maintenancetool",
        // Hosts, stubs and crash handlers that front for something else.
        "applaunch",
        "dllhost",
        "rundll32",
        "lnkstub",
        "werfault",
        "dfsvc",
        "guestmodemsg",
        "msoobe",
        "wlrmdr",
        "wuapp",
        // Help viewers.
        "hh",
        "winhlp32",
    ];
    // `unins000`, `unins001`… are Inno Setup's uninstallers, and `uninstall` /
    // `uninst` cover the rest; a prefix test rather than equality because the
    // numeric suffix varies per install.
    stem.starts_with("unins") || stem.contains("uninstall") || NEVER.contains(&stem)
}

/// Classify one Start-menu entry into a catalogue row, or `None` if it is not an
/// application Grain could ever recognise in the foreground.
///
/// Split out from the COM walk so the rules are testable without a shell: the
/// inputs here are exactly the two strings the walk reads off each item.
fn classify(name: &str, target_path: &str, aumid: &str) -> Option<InstalledApp> {
    let name = name.trim();
    if name.is_empty() {
        return None;
    }
    let target_path = target_path.trim();

    // A shortcut with an executable behind it: a desktop app. Checked FIRST,
    // because these also carry an AppUserModelID and it is the wrong identity to
    // match on — `GetApplicationUserModelId` reports nothing for an unpackaged
    // process, so a profile keyed on Chrome's `Chrome` AUMID would never fire.
    if target_path.to_ascii_lowercase().ends_with(".exe") {
        let stem = std::path::Path::new(target_path)
            .file_stem()
            .and_then(|s| s.to_str())?
            .to_ascii_lowercase();
        if stem.is_empty() || is_not_an_app(&stem) {
            return None;
        }
        return Some(InstalledApp {
            name: name.to_string(),
            target: stem,
            icon_id: target_path.to_string(),
        });
    }

    // No executable behind it. A packaged app is the legitimate case — it has no
    // shortcut, only an identity — and the `!` separating package family from
    // application id is what distinguishes one from a desktop entry's opaque
    // AppUserModelID.
    let aumid = aumid.trim();
    if aumid.contains('!') {
        return Some(InstalledApp {
            name: name.to_string(),
            target: aumid.to_string(),
            icon_id: aumid.to_string(),
        });
    }

    // Everything else: documentation, readmes, web links, folders, management
    // consoles. Real Start menu entries, but not things text is dictated into.
    None
}

/// Sort by name and drop rows that would match the same window.
///
/// Two entries sharing a target are the same app to the matcher — "Windows
/// PowerShell" and "Windows PowerShell (x86)" both resolve to `powershell` — and
/// offering both would let someone pick the qualified one and quietly get the
/// other as well. The shorter name wins, which is the unqualified base product
/// in every case this collapses.
fn dedupe(mut apps: Vec<InstalledApp>) -> Vec<InstalledApp> {
    apps.sort_by(|a, b| {
        a.target
            .cmp(&b.target)
            .then_with(|| a.name.chars().count().cmp(&b.name.chars().count()))
            .then_with(|| a.name.cmp(&b.name))
    });
    apps.dedup_by(|a, b| a.target == b.target);
    apps.sort_by(|a, b| a.name.to_lowercase().cmp(&b.name.to_lowercase()));
    apps
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The identity rule, stated once as a test because getting it backwards is
    /// silent: the profile saves, the card looks right, and it never fires.
    #[test]
    fn a_desktop_app_is_keyed_on_its_exe_even_when_it_has_an_appusermodelid() {
        // Chrome's own AppUserModelID is the bare string `Chrome`, and matching
        // on it would never fire — an unpackaged process reports no AUMID.
        let app = classify(
            "Google Chrome",
            r"C:\Program Files\Google\Chrome\Application\chrome.exe",
            "Chrome",
        )
        .unwrap();
        assert_eq!(app.target, "chrome");
        assert_eq!(
            app.icon_id,
            r"C:\Program Files\Google\Chrome\Application\chrome.exe"
        );
    }

    /// A shortcut with arguments gets a generated identity that names nothing.
    /// The target path is the reason these are still usable.
    #[test]
    fn an_opaque_entry_still_resolves_through_its_target_path() {
        for (name, path, aumid) in [
            (
                "Git Bash",
                r"C:\Program Files\Git\git-bash.exe",
                "Microsoft.AutoGenerated.{0FDD9C6B}",
            ),
            (
                "Zen",
                r"C:\Program Files\Zen Browser\zen.exe",
                "F0DC299D809B9700",
            ),
        ] {
            let app = classify(name, path, aumid)
                .unwrap_or_else(|| panic!("{name} should classify as an app"));
            assert!(!app.target.contains('!') && !app.target.contains('{'));
        }
    }

    #[test]
    fn a_packaged_app_is_keyed_on_the_aumid_detection_will_report() {
        let app = classify("Claude", "", "Claude_pzs8sxrjxfjjc!Claude").unwrap();
        assert_eq!(app.target, "Claude_pzs8sxrjxfjjc!Claude");
        assert_eq!(
            app.icon_id, app.target,
            "packaged icons resolve by identity"
        );
    }

    /// The Start menu carries plenty of these, and every one of them would be a
    /// row that can never match anything.
    #[test]
    fn things_that_are_not_applications_are_dropped() {
        for (name, path) in [
            ("Read Me", r"C:\VulkanSDK\README.txt"),
            ("Inno Setup Documentation", r"C:\Inno Setup 6\ISetup.chm"),
            ("Python Manuals", r"C:\Python314\Doc\html\index.html"),
            ("Inno Setup FAQ", r"C:\Inno Setup 6\isfaq.url"),
            ("Example Scripts", r"C:\Inno Setup 6\Examples"),
            ("Services", r"C:\Windows\system32\services.msc"),
            ("Run Icecast", r"C:\Icecast\icecast.bat"),
            ("Uninstall Grain", r"C:\Program Files\Grain\unins000.exe"),
            ("Uninstall IDM", r"C:\IDM\Uninstall.exe"),
            ("Maintenance Tool", r"C:\VulkanSDK\maintenancetool.exe"),
            ("Uninstall Node.js", r"C:\Windows\system32\msiexec.exe"),
        ] {
            assert_eq!(classify(name, path, ""), None, "{name} should be dropped");
        }
        // A web link has neither a target nor a packaged identity.
        assert_eq!(classify("Node.js website", "", "https://nodejs.org/"), None);
        assert_eq!(classify("", r"C:\x\a.exe", ""), None, "unnamed is unusable");
    }

    #[test]
    fn entries_that_would_match_the_same_window_collapse_to_the_shortest_name() {
        let app = |name: &str, target: &str| InstalledApp {
            name: name.into(),
            target: target.into(),
            icon_id: target.into(),
        };
        let got = dedupe(vec![
            app("Windows PowerShell (x86)", "powershell"),
            app("Visual Studio Code", "code"),
            app("Windows PowerShell", "powershell"),
        ]);
        assert_eq!(
            got.iter().map(|a| a.name.as_str()).collect::<Vec<_>>(),
            vec!["Visual Studio Code", "Windows PowerShell"],
            "one row per target, sorted by name"
        );
    }
}

// ── Windows ─────────────────────────────────────────────────────────────────

#[cfg(windows)]
mod windows_impl {
    use super::{classify, dedupe, InstalledApp};
    use windows::core::{w, Interface, GUID, PWSTR};
    use windows::Win32::Foundation::PROPERTYKEY;
    use windows::Win32::System::Com::{
        CoInitializeEx, CoTaskMemFree, CoUninitialize, COINIT_APARTMENTTHREADED,
    };
    use windows::Win32::UI::Shell::{
        BHID_EnumItems, IEnumShellItems, IShellItem, IShellItem2, SHCreateItemFromParsingName,
        SIGDN_NORMALDISPLAY,
    };

    /// The two shell properties this module reads, declared here rather than
    /// imported.
    ///
    /// The `windows` crate files them under a feature (`Win32_Storage_EnhancedStorage`)
    /// whose name has nothing to do with what they are, and turning it on — plus
    /// `Win32_UI_Shell_PropertiesSystem` — meant five more lines in the
    /// Handy-derived `Cargo.toml`, which is the one place Grain is trying not to
    /// grow. Two constants cost less than two crate features, and a property key
    /// is a published, frozen identifier: these are the values in the
    /// `System.Link.TargetParsingPath` and `System.AppUserModel.ID` docs, and
    /// they cannot change without breaking every shell client on Windows.
    const PKEY_LINK_TARGET_PARSING_PATH: PROPERTYKEY = PROPERTYKEY {
        fmtid: GUID::from_u128(0xb9b4b3fc_2b51_4a42_b5d8_324146afcf25),
        pid: 2,
    };
    const PKEY_APP_USER_MODEL_ID: PROPERTYKEY = PROPERTYKEY {
        fmtid: GUID::from_u128(0x9f4c2855_9f79_4b39_a8d0_e1d42de1d5f3),
        pid: 5,
    };

    /// Items per `Next` call. One COM round-trip per app would double the cost
    /// of the walk for nothing; a machine's whole Start menu is a few hundred.
    const BATCH: usize = 32;

    /// Refuses to run away on a pathological namespace. A real machine is in the
    /// low hundreds, so this can only ever be hit by something going wrong.
    const MAX_ITEMS: usize = 4096;

    pub fn enumerate() -> Vec<InstalledApp> {
        unsafe {
            // Our own thread, so our own apartment — same reasoning as the icon
            // resolver: nothing else in this process has initialised COM here.
            let co = CoInitializeEx(None, COINIT_APARTMENTTHREADED);
            let apps = walk();
            if co.is_ok() {
                CoUninitialize();
            }
            dedupe(apps)
        }
    }

    unsafe fn walk() -> Vec<InstalledApp> {
        let Ok(folder) =
            SHCreateItemFromParsingName::<_, _, IShellItem>(w!("shell:AppsFolder"), None)
        else {
            return Vec::new();
        };
        let Ok(items) = folder.BindToHandler::<_, IEnumShellItems>(None, &BHID_EnumItems) else {
            return Vec::new();
        };

        let mut out = Vec::new();
        let mut seen = 0usize;
        loop {
            // A fresh buffer each pass: `Next` writes raw pointers over the
            // slice without dropping what was there, so reusing one would leak
            // an interface per batch.
            let mut batch: [Option<IShellItem>; BATCH] = std::array::from_fn(|_| None);
            let mut fetched = 0u32;
            // S_FALSE is a success code and means "fewer than asked for", so the
            // count — not the HRESULT — is what ends the walk.
            if items.Next(&mut batch, Some(&mut fetched)).is_err() || fetched == 0 {
                break;
            }
            for item in batch.into_iter().take(fetched as usize).flatten() {
                if let Some(app) = row(&item) {
                    out.push(app);
                }
            }
            seen += fetched as usize;
            if (fetched as usize) < BATCH || seen >= MAX_ITEMS {
                break;
            }
        }
        out
    }

    /// One shell item → one catalogue row, or `None`.
    unsafe fn row(item: &IShellItem) -> Option<InstalledApp> {
        let name = take(item.GetDisplayName(SIGDN_NORMALDISPLAY).ok()?)?;
        // The properties live on IShellItem2; an item that does not support it
        // cannot be identified, which is a reason to skip it rather than guess.
        let item2: IShellItem2 = item.cast().ok()?;
        // Both are absent on plenty of entries — a desktop app has no packaged
        // identity, a packaged app has no target — so a failure here is the
        // normal case and `classify` is what decides which combination is usable.
        let target = item2
            .GetString(&PKEY_LINK_TARGET_PARSING_PATH)
            .ok()
            .and_then(|p| take(p))
            .unwrap_or_default();
        let aumid = item2
            .GetString(&PKEY_APP_USER_MODEL_ID)
            .ok()
            .and_then(|p| take(p))
            .unwrap_or_default();
        classify(&name, &target, &aumid)
    }

    /// Copy a shell-allocated string out and free it. Every one of these comes
    /// from an API documented as transferring ownership, so the free is not
    /// optional — a Start menu's worth of leaks per picker open would be real.
    unsafe fn take(p: PWSTR) -> Option<String> {
        if p.is_null() {
            return None;
        }
        let s = p.to_string().ok();
        CoTaskMemFree(Some(p.0 as *const std::ffi::c_void));
        s.filter(|s| !s.trim().is_empty())
    }
}
