//! [GRAIN] Where a locale tag resolves to — decided once, in Rust.
//!
//! The rule ("`zh-Hant-*` and `zh-HK/MO/TW` mean Traditional Chinese;
//! Cantonese follows Traditional unless tagged Hans") existed twice: here-ish,
//! in `tray_i18n::get_tray_translations`, and again in TypeScript in
//! `src/i18n/index.ts`. Upstream fixed the *TypeScript* copy in `ea3c20a3`
//! (#1798) — a change Grain now has to port by hand, because the frontend is
//! frozen. That is exactly the class of fix the freeze plan says belongs in the
//! backend: it is a fact about how a system locale tag maps to a catalogue, not
//! a decision about how a screen looks.
//!
//! So this module owns the rule and exposes it as a command; the frontend asks
//! rather than re-deriving. `tray_i18n` keeps its own copy — it is inside the
//! byte-frozen Handy tree and cannot call out — but `agrees_with_tray` pins the
//! two together, so if upstream ever changes the rule there, this fails to
//! agree instead of quietly disagreeing in a user's menu.
//!
//! The set of locales that exist is not hardcoded either: `TRANSLATIONS` is
//! generated by `build.rs` from `src/i18n/locales/*/translation.json`, the same
//! files the frontend globs. One source of truth for *which* locales, one for
//! *how* a tag maps onto them.

/// Resolve a system or user locale tag onto one of `available`.
///
/// Returns `None` when nothing matches, which the caller should read as "use
/// the fallback language", not as an error.
pub fn resolve(tag: &str, available: &[&str]) -> Option<String> {
    let normalized = tag.to_lowercase().replace('_', "-");
    let subtags: Vec<_> = normalized.split('-').collect();
    let language = subtags.first().copied().unwrap_or_default();
    let is_hant = subtags.contains(&"hant");
    let is_hans = subtags.contains(&"hans");
    let is_traditional_region = ["tw", "hk", "mo"]
        .iter()
        .any(|region| subtags.contains(region));

    // An exact match wins outright — `zh-TW` is a catalogue, not a fallback.
    if let Some(code) = available
        .iter()
        .find(|code| code.eq_ignore_ascii_case(&normalized))
    {
        return Some((*code).to_string());
    }

    let fallback = match language {
        "zh" if is_hant || (!is_hans && is_traditional_region) => "zh-tw",
        // Cantonese uses Traditional Chinese unless explicitly tagged as Hans.
        "yue" if is_hans => "zh",
        "yue" => "zh-tw",
        other => other,
    };

    available
        .iter()
        .find(|code| code.eq_ignore_ascii_case(fallback))
        .map(|code| (*code).to_string())
}

/// Every locale this build ships a catalogue for.
fn available() -> Vec<&'static str> {
    let mut codes: Vec<&'static str> = crate::tray_i18n::TRANSLATIONS.keys().copied().collect();
    codes.sort_unstable();
    codes
}

/// Resolve a locale tag onto a shipped catalogue. `None` in, or nothing
/// matching, means the caller should use its fallback language.
#[tauri::command]
#[specta::specta]
pub async fn resolve_app_locale(tag: Option<String>) -> Option<String> {
    resolve(tag.as_deref()?, &available())
}

#[cfg(test)]
mod tests {
    use super::*;

    const AVAILABLE: &[&str] = &["en", "es", "zh", "zh-TW", "ja", "de"];

    #[test]
    fn exact_match_wins() {
        assert_eq!(resolve("zh-TW", AVAILABLE).as_deref(), Some("zh-TW"));
        assert_eq!(resolve("ZH-tw", AVAILABLE).as_deref(), Some("zh-TW"));
        assert_eq!(resolve("en", AVAILABLE).as_deref(), Some("en"));
    }

    #[test]
    fn traditional_chinese_by_script_or_region() {
        for tag in [
            "zh-Hant-TW",
            "zh-Hant-HK",
            "zh-HK",
            "zh-MO",
            "zh_Hant_TW",
            "yue-Hant-HK",
            "yue",
        ] {
            assert_eq!(
                resolve(tag, AVAILABLE).as_deref(),
                Some("zh-TW"),
                "{tag} should resolve to Traditional Chinese"
            );
        }
        // Explicitly Simplified stays Simplified, region notwithstanding.
        assert_eq!(resolve("zh-Hans-HK", AVAILABLE).as_deref(), Some("zh"));
        assert_eq!(resolve("yue-Hans", AVAILABLE).as_deref(), Some("zh"));
        assert_eq!(resolve("zh-CN", AVAILABLE).as_deref(), Some("zh"));
    }

    #[test]
    fn region_falls_back_to_language() {
        assert_eq!(resolve("es-419", AVAILABLE).as_deref(), Some("es"));
        assert_eq!(resolve("de-AT", AVAILABLE).as_deref(), Some("de"));
    }

    #[test]
    fn unknown_is_none_not_english() {
        // The caller decides the fallback; silently answering "en" here would
        // hide a missing catalogue from whoever asked.
        assert_eq!(resolve("sw-KE", AVAILABLE), None);
        assert_eq!(resolve("", AVAILABLE), None);
    }

    /// The frozen Handy copy of this rule lives in `tray_i18n` and cannot call
    /// out to us. Pin them together: for every tag, the catalogue this resolver
    /// picks must be the one the tray actually renders. If upstream edits the
    /// rule there, this fails rather than the two silently disagreeing.
    #[test]
    fn agrees_with_tray() {
        let codes = available();
        for tag in [
            "zh-Hant-TW", "zh-Hant-HK", "zh-HK", "zh-MO", "ZH-TW", "zh_Hant_TW", "zh-Hans-HK",
            "yue-Hant-HK", "yue", "zh-CN", "en-GB", "de-AT", "ja", "sw-KE",
        ] {
            let ours = resolve(tag, &codes).unwrap_or_else(|| "en".to_string());
            let theirs = crate::tray_i18n::get_tray_translations(Some(tag.to_string()));
            let expected = crate::tray_i18n::TRANSLATIONS
                .get(ours.as_str())
                .expect("resolved code must have a catalogue");
            assert_eq!(
                format!("{expected:?}"),
                format!("{theirs:?}"),
                "{tag}: resolver chose {ours}, which is not what the tray renders"
            );
        }
    }
}
