
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async changeBinding(id: string, binding: string) : Promise<Result<BindingResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_binding", { id, binding }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resetBinding(id: string) : Promise<Result<BindingResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reset_binding", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changePttSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_ptt_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeAudioFeedbackSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_audio_feedback_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeAudioFeedbackVolumeSetting(volume: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_audio_feedback_volume_setting", { volume }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeSoundThemeSetting(theme: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_sound_theme_setting", { theme }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeDefaultPanelSetting(panel: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_default_panel_setting", { panel }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeStartHiddenSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_start_hidden_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeAutostartSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_autostart_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeTranslateToEnglishSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_translate_to_english_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeSelectedLanguageSetting(language: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_selected_language_setting", { language }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeOverlayPositionSetting(position: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_overlay_position_setting", { position }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeDebugModeSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_debug_mode_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeWordCorrectionThresholdSetting(threshold: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_word_correction_threshold_setting", { threshold }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeExtraRecordingBufferSetting(ms: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_extra_recording_buffer_setting", { ms }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changePasteDelayMsSetting(ms: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_paste_delay_ms_setting", { ms }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changePasteMethodSetting(method: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_paste_method_setting", { method }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAvailableTypingTools() : Promise<string[]> {
    return await TAURI_INVOKE("get_available_typing_tools");
},
async changeTypingToolSetting(tool: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_typing_tool_setting", { tool }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeExternalScriptPathSetting(path: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_external_script_path_setting", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeClipboardHandlingSetting(handling: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_clipboard_handling_setting", { handling }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeAutoSubmitSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_auto_submit_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeAutoSubmitKeySetting(key: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_auto_submit_key_setting", { key }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changePostProcessEnabledSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_post_process_enabled_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * [GRAIN] Master toggle for Grain Space. Registers/unregisters the feature's
 * global shortcuts immediately so OFF is zero-overhead without a restart.
 * Never touches on-disk note data.
 */
async changeGrainSpaceEnabledSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_grain_space_enabled_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * [GRAIN] Grain Space semantic-search toggle. Flips the setting; the model
 * download (opt-in consent flow) is driven by the frontend before it turns
 * this on. OFF must guarantee the embedding model never loads — any resident
 * engine is dropped immediately.
 */
async changeGrainSpaceSemanticSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_grain_space_semantic_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * [GRAIN] Auto-arm reminders extracted from captured notes (vs. manual arm).
 */
async changeGrainSpaceAutoRemindersSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_grain_space_auto_reminders_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * [GRAIN] Voice-first retrieval behavior (Phase 5): results list vs AI Q&A.
 */
async changeGrainSpaceRetrievalModeSetting(mode: GrainSpaceRetrievalMode) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_grain_space_retrieval_mode_setting", { mode }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async grainSpaceListNotes() : Promise<Result<Note[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("grain_space_list_notes") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async grainSpaceSearchNotes(query: string) : Promise<Result<Note[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("grain_space_search_notes", { query }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async grainSpaceGetNote(id: string) : Promise<Result<Note, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("grain_space_get_note", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Create or update. The frontend sends the full locked-schema note; for new
 * notes it uses `grain_space_create_note` instead so ids stay backend-minted.
 */
async grainSpaceSaveNote(note: Note) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("grain_space_save_note", { note }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Mint a new raw note (blank title/tldr) and return it for editing.
 */
async grainSpaceCreateNote(body: string) : Promise<Result<Note, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("grain_space_create_note", { body }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async grainSpaceDeleteNote(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("grain_space_delete_note", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async grainSpaceSetPinned(id: string, pinned: boolean) : Promise<Result<Note, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("grain_space_set_pinned", { id, pinned }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Arm (or re-arm) a note's reminder at `fire_at` (epoch ms).
 */
async grainSpaceArmReminder(id: string, fireAt: number) : Promise<Result<Note, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("grain_space_arm_reminder", { id, fireAt }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Dismiss/complete a reminder (fired, armed, or pending).
 */
async grainSpaceDismissReminder(id: string) : Promise<Result<Note, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("grain_space_dismiss_reminder", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Recovery: re-derive the whole index from the JSON files.
 */
async grainSpaceRebuildIndex() : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("grain_space_rebuild_index") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Open the overlay (or refocus it), optionally landing on a note. Used by the
 * settings tab's note rows; the global shortcut uses the toggle action.
 */
async grainSpaceOpenWindow(noteId: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("grain_space_open_window", { noteId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Close (destroy) the overlay. Deliberately NOT gated: the window must be
 * closable even if the feature was just disabled underneath it.
 */
async grainSpaceCloseWindow() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("grain_space_close_window") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * One-shot: the note id the overlay should select on mount, if any.
 */
async grainSpaceTakeFocusNote() : Promise<string | null> {
    return await TAURI_INVOKE("grain_space_take_focus_note");
},
async grainSpaceEmbedModelStatus() : Promise<EmbedModelStatus> {
    return await TAURI_INVOKE("grain_space_embed_model_status");
},
/**
 * Consent-gated model download (the frontend shows the consent dialog BEFORE
 * calling this). Progress/completion/error arrive as events; resolves when
 * the transfer ends either way.
 */
async grainSpaceDownloadEmbedModel() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("grain_space_download_embed_model") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async grainSpaceCancelEmbedModelDownload() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("grain_space_cancel_embed_model_download") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Semantic (meaning-based) search. Spawns the engine lazily on first use —
 * allowed only while the overlay window exists, so the weights can never
 * outlive it. Re-embeds stale notes before serving so results stay truthful.
 */
async grainSpaceSemanticSearch(query: string) : Promise<Result<Note[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("grain_space_semantic_search", { query }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeExperimentalEnabledSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_experimental_enabled_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changePostProcessBaseUrlSetting(providerId: string, baseUrl: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_post_process_base_url_setting", { providerId, baseUrl }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changePostProcessApiKeySetting(providerId: string, apiKey: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_post_process_api_key_setting", { providerId, apiKey }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changePostProcessModelSetting(providerId: string, model: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_post_process_model_setting", { providerId, model }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setPostProcessProvider(providerId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_post_process_provider", { providerId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async fetchPostProcessModels(providerId: string) : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fetch_post_process_models", { providerId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addPostProcessPrompt(name: string, prompt: string) : Promise<Result<LLMPrompt, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_post_process_prompt", { name, prompt }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updatePostProcessPrompt(id: string, name: string, prompt: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_post_process_prompt", { id, name, prompt }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deletePostProcessPrompt(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_post_process_prompt", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setPostProcessSelectedPrompt(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_post_process_selected_prompt", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateCustomWords(words: string[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_custom_words", { words }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateSnippets(snippets: Snippet[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_snippets", { snippets }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * [GRAIN] Persist the user's voice actions (trigger → open apps/sites). Drops
 * entries with a blank trigger or no targets, and prunes blank target values —
 * the UI enforces this too, but this guards direct invoke calls.
 */
async updateActions(actions: VoiceAction[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_actions", { actions }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * [GRAIN] Open a set of targets on demand — powers the Settings "Test" button so
 * a user can confirm an action before saving it.
 */
async runAction(targets: ActionTarget[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("run_action", { targets }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * [GRAIN] Native file picker for choosing an application/executable to launch,
 * so users never have to type a path. Returns the absolute path, or `None` if
 * the dialog was cancelled. Runs the modal off the async executor.
 */
async pickActionApp() : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pick_action_app") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * [GRAIN] Toggle context awareness (post-processing SOFT context + user MODES).
 */
async changeContextAwarenessEnabledSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_context_awareness_enabled_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * [GRAIN] Toggle the silent nearby-term hints (reads focused-field unique tokens
 * via UI Automation). Only effective when context awareness is also on.
 */
async changeContextNearbyTermsSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_context_nearby_terms_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * [GRAIN] Agent auto-copy policy (off / first reply / all replies).
 */
async changeAgentAutocopySetting(mode: AgentAutocopy) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_agent_autocopy_setting", { mode }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * [GRAIN] Toggle Quick Agent (palette submit → headless AI run → paste at cursor).
 */
async changeAgentQuickEnabledSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_agent_quick_enabled_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * [GRAIN] Agent context awareness mode (off / unique terms / full field text).
 */
async changeAgentContextModeSetting(mode: AgentContextMode) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_agent_context_mode_setting", { mode }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * [GRAIN] Toggle "type to expand" on the native agent input.
 */
async changeAgentInputTypeToExpandSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_agent_input_type_to_expand_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * [GRAIN] Toggle auto-add-to-dictionary. Off = zero overhead (no watcher spawns).
 */
async changeAutoDictionaryEnabledSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_auto_dictionary_enabled_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * [GRAIN] Toggle the "scrap that" voice reset. Off = zero overhead (the snippet
 * matcher is never invoked for it and the live preview takes its normal path).
 */
async changeScrapThatEnabledSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_scrap_that_enabled_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * [GRAIN] Persist the user's per-app / per-site modes (hard formatting). Drops
 * entries missing a name, prompt, or a non-blank matcher value — the UI enforces
 * this too, but this guards direct invoke calls.
 */
async updateAppModes(modes: AppMode[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_app_modes", { modes }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * [GRAIN] Detect the foreground app right now. Returns `None` when nothing can be
 * resolved (unsupported platform, no foreground window). Silent — no UI.
 */
async detectActiveApp() : Promise<DetectedApp | null> {
    return await TAURI_INVOKE("detect_active_app");
},
/**
 * Temporarily unregister a binding while the user is editing it in the UI.
 * This avoids firing the action while keys are being recorded.
 */
async suspendBinding(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("suspend_binding", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Re-register the binding after the user has finished editing.
 */
async resumeBinding(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resume_binding", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeMuteWhileRecordingSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_mute_while_recording_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * [GRAIN] Toggle voice conditioning (85 Hz high-pass + boost-only AGC for quiet
 * mics). Persists the setting and live-updates the open recorder so it applies
 * to the next captured frame without a restart. (Rolling re-reads it per session.)
 */
async changeAudioConditioningSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_audio_conditioning_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeAppendTrailingSpaceSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_append_trailing_space_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * [GRAIN] Toggle the rolling live preview (Studio Window caption during
 * rolling dictation). Persisted only; each rolling session reads it at start,
 * so OFF sessions never spawn the preview machinery — zero compute overhead.
 */
async changeRollingLivePreviewSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_rolling_live_preview_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeLazyStreamCloseSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_lazy_stream_close_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeAppLanguageSetting(language: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_app_language_setting", { language }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeUpdateChecksSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_update_checks_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Change the keyboard implementation with runtime switching.
 * This will unregister all shortcuts from the old implementation,
 * validate shortcuts for the new implementation (resetting invalid ones to defaults),
 * and register them with the new implementation.
 */
async changeKeyboardImplementationSetting(implementation: string) : Promise<Result<ImplementationChangeResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_keyboard_implementation_setting", { implementation }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get the current keyboard implementation
 */
async getKeyboardImplementation() : Promise<string> {
    return await TAURI_INVOKE("get_keyboard_implementation");
},
async changeShowTrayIconSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_show_tray_icon_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeTranscribeAcceleratorSetting(accelerator: TranscribeAcceleratorSetting) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_transcribe_accelerator_setting", { accelerator }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeTranscribeGpuDevice(device: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_transcribe_gpu_device", { device }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Return which accelerators and GPU devices are available for this build.
 * 
 * First-call cost is dominated by enumerating GPU devices through the
 * transcribe.cpp Metal/Vulkan backend, which loads dynamic libraries and
 * probes hardware. Run it on the blocking pool so the webview thread
 * stays responsive — see also the startup pre-warm in `lib.rs`.
 */
async getAvailableAccelerators() : Promise<AvailableAccelerators> {
    return await TAURI_INVOKE("get_available_accelerators");
},
/**
 * Start key recording mode
 */
async startHandyKeysRecording(bindingId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_handy_keys_recording", { bindingId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Stop key recording mode
 */
async stopHandyKeysRecording() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_handy_keys_recording") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async showMainWindowCommand() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("show_main_window_command") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The selection captured at summon (non-consuming): the palette reads its length
 * for the char-count chip, the panel reads the text as LLM context.
 */
async agentGetContext() : Promise<string | null> {
    return await TAURI_INVOKE("agent_get_context");
},
/**
 * Consume the first instruction (the panel calls this on mount).
 */
async agentTakeInstruction() : Promise<string | null> {
    return await TAURI_INVOKE("agent_take_instruction");
},
/**
 * Copy text to the clipboard (used for the auto-copy of the first reply and the
 * per-message copy buttons).
 */
async agentCopy(text: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("agent_copy", { text }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Run the conversation against the configured AI and return the assistant reply.
 * Uses the post-processing provider config: a single provider, or the smart
 * rotation pool (round-robin + daily quota + health-ordered failover). The
 * focused-field context captured at summon (if any) is injected backend-side.
 */
async agentRun(messages: AgentMessage[], context: string | null) : Promise<Result<AgentReply, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("agent_run", { messages, context }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Resize/reposition the panel between the COMPACT reply card and the EXPANDED
 * conversation, and swap the global Enter accordingly: compact owns a global
 * Enter (= Confirm/paste); expanded owns an in-window input, so a registered
 * global Enter would swallow the user's keystrokes.
 * 
 * ASYNC on purpose: a sync command runs on the MAIN thread, and calling
 * `set_size` on a visible window from inside a command on the main thread
 * deadlocks on Windows (tauri#3990 / tao#381) — that was the "panel ghosts a
 * few seconds after expanding" freeze. On a runtime worker the window ops are
 * proxied to the event loop safely.
 */
async agentSetPanelMode(expanded: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("agent_set_panel_mode", { expanded }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Confirm (⏎ on the reply card): close the panel, refocus the summon target,
 * and paste `text` — the latest assistant reply — at the cursor. A selection
 * still held in the target app is replaced by the paste.
 */
async agentConfirmPaste(text: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("agent_confirm_paste", { text }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Consume the retained Quick-Agent conversation (the panel calls this on
 * mount). Non-empty only when the panel is reopening from a follow-up offer —
 * in that case the panel starts EXPANDED with this history.
 */
async agentTakeConversation() : Promise<AgentMessage[]> {
    return await TAURI_INVOKE("agent_take_conversation");
},
async cancelOperation() : Promise<void> {
    await TAURI_INVOKE("cancel_operation");
},
async isPortable() : Promise<boolean> {
    return await TAURI_INVOKE("is_portable");
},
async getAppDirPath() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_app_dir_path") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAppSettings() : Promise<Result<AppSettings, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_app_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async sttGetPool() : Promise<Result<SttPoolView, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stt_get_pool") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async sttSetSmartRotation(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stt_set_smart_rotation", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Add or update a cloud provider (matched by `id`), optionally setting its API
 * key (written to grain.secrets.json). The local provider is managed
 * automatically and cannot be created/edited here.
 */
async sttUpsertProvider(provider: SttProvider, apiKey: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stt_upsert_provider", { provider, apiKey }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async sttRemoveProvider(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stt_remove_provider", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async ppGetPool() : Promise<Result<PpPoolView, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pp_get_pool") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async ppSetSmartRotation(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pp_set_smart_rotation", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Add or update a post-process provider (matched by `id`), optionally setting its
 * API key (→ grain.secrets.json) and model (→ `post_process_models`). Two entries
 * with the same `base_url` but different `id`s = two keys for one endpoint, which
 * is how multi-key rotation is expressed.
 */
async ppUpsertProvider(provider: PostProcessProvider, apiKey: string | null, model: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pp_upsert_provider", { provider, apiKey, model }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async ppRemoveProvider(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pp_remove_provider", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getDefaultSettings() : Promise<Result<AppSettings, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_default_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getLogDirPath() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_log_dir_path") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setLogLevel(level: LogLevel) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_log_level", { level }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openRecordingsFolder() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_recordings_folder") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openLogDir() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_log_dir") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openAppDataDir() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_app_data_dir") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Check if Apple Intelligence is available on this device.
 * Called by the frontend when the user selects Apple Intelligence provider.
 */
async checkAppleIntelligenceAvailable() : Promise<boolean> {
    return await TAURI_INVOKE("check_apple_intelligence_available");
},
/**
 * Try to initialize Enigo (keyboard/mouse simulation).
 * On macOS, this will return an error if accessibility permissions are not granted.
 */
async initializeEnigo() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("initialize_enigo") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Initialize keyboard shortcuts.
 * On macOS, this should be called after accessibility permissions are granted.
 * This is idempotent - calling it multiple times is safe.
 */
async initializeShortcuts() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("initialize_shortcuts") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAvailableModels() : Promise<Result<ModelInfo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_available_models") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getModelInfo(modelId: string) : Promise<Result<ModelInfo | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_model_info", { modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async downloadModel(modelId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("download_model", { modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteModel(modelId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_model", { modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cancelDownload(modelId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cancel_download", { modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setActiveModel(modelId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_active_model", { modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getCurrentModel() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_current_model") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getTranscriptionModelStatus() : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_transcription_model_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async isModelLoading() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("is_model_loading") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async hasAnyModelsAvailable() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("has_any_models_available") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async hasAnyModelsOrDownloads() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("has_any_models_or_downloads") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Re-scan local sources (custom models dir + shared HF cache) for models added
 * since launch
 */
async rescanLocalModels() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("rescan_local_models") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The streaming slice of the unified model catalog (`supports_streaming`),
 * for the "Streaming model" section of Settings → Speech to Text.
 */
async listAsrModels() : Promise<Result<ModelInfo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_asr_models") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Persist the selected streaming model. Accepts any catalog id (download may
 * happen afterward); the shortcut's start path checks it is actually on disk.
 * Hard category guard: only streaming-capable models may become
 * `selected_asr_model` (the mirror of `switch_active_model`'s standard-only
 * guard). Clearing the selection with an empty id is always allowed.
 */
async selectAsrModel(modelId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("select_asr_model", { modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateMicrophoneMode(alwaysOn: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_microphone_mode", { alwaysOn }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getMicrophoneMode() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_microphone_mode") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getWindowsMicrophonePermissionStatus() : Promise<WindowsMicrophonePermissionStatus> {
    return await TAURI_INVOKE("get_windows_microphone_permission_status");
},
async openMicrophonePrivacySettings() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_microphone_privacy_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAvailableMicrophones() : Promise<Result<AudioDevice[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_available_microphones") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setSelectedMicrophone(deviceName: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_selected_microphone", { deviceName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSelectedMicrophone() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_selected_microphone") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAvailableOutputDevices() : Promise<Result<AudioDevice[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_available_output_devices") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setSelectedOutputDevice(deviceName: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_selected_output_device", { deviceName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSelectedOutputDevice() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_selected_output_device") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async playTestSound(soundType: string) : Promise<void> {
    await TAURI_INVOKE("play_test_sound", { soundType });
},
async checkCustomSounds() : Promise<CustomSounds> {
    return await TAURI_INVOKE("check_custom_sounds");
},
async setClamshellMicrophone(deviceName: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_clamshell_microphone", { deviceName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getClamshellMicrophone() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_clamshell_microphone") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async isRecording() : Promise<boolean> {
    return await TAURI_INVOKE("is_recording");
},
async setModelUnloadTimeout(timeout: ModelUnloadTimeout) : Promise<void> {
    await TAURI_INVOKE("set_model_unload_timeout", { timeout });
},
async getModelLoadStatus() : Promise<Result<ModelLoadStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_model_load_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async unloadModelManually() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("unload_model_manually") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getHistoryEntries(cursor: number | null, limit: number | null) : Promise<Result<PaginatedHistory, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_history_entries", { cursor, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async toggleHistoryEntrySaved(id: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("toggle_history_entry_saved", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAudioFilePath(fileName: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_audio_file_path", { fileName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteHistoryEntry(id: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_history_entry", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async retryHistoryEntryTranscription(id: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("retry_history_entry_transcription", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateHistoryLimit(limit: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_history_limit", { limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateRecordingRetentionPeriod(period: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_recording_retention_period", { period }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Stub implementation for non-macOS platforms
 * Always returns false since laptop detection is macOS-specific
 */
async isLaptop() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("is_laptop") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
historyUpdatePayload: HistoryUpdatePayload,
streamTextEvent: StreamTextEvent
}>({
historyUpdatePayload: "history-update-payload",
streamTextEvent: "stream-text-event"
})

/** user-defined constants **/



/** user-defined types **/

/**
 * [GRAIN] One thing a voice ACTION opens. `App` is launched with the OS default
 * handler (an executable, a document, or a folder — cross-platform via the
 * opener); `Url` is opened in the user's default browser. Kept as a two-variant
 * enum so the UI stays a single App/Website toggle (childishly simple).
 */
export type ActionTarget = { kind: "app"; value: string } | { kind: "url"; value: string }
/**
 * [GRAIN] Agent auto-copy policy: which assistant replies are copied to the
 * clipboard automatically as they arrive. `First` (default) mirrors the
 * original behavior — only the first reply of a session is auto-copied.
 */
export type AgentAutocopy = "off" | "first" | "all"
/**
 * [GRAIN] Agent context awareness: what (if anything) is read from the focused
 * field at summon and handed to the LLM as background. `Unique` reuses the
 * nearby-terms extractor (high-signal identifiers/names only); `Full` sends the
 * capped raw field text. OFF by default — reading field content is opt-in.
 */
export type AgentContextMode = "off" | "unique" | "full"
/**
 * One conversation turn from the frontend.
 */
export type AgentMessage = { 
/**
 * `"user"` or `"assistant"` (anything else is treated as `"user"`).
 */
role: string; content: string }
/**
 * The panel's per-turn reply. `text` is the display answer (any Recall
 * convention line already stripped). `sources` + `not_found` drive Recall's
 * evidence footer / escape hatch (RECALL-PLAN §6); Assist always returns an
 * empty `sources` and `not_found = false`, so the panel renders no footer.
 */
export type AgentReply = { text: string; sources: AgentSource[]; not_found: boolean; 
/**
 * Set only by a Grain Recall `forget` turn (RECALL-PLAN §7.2): the memory
 * the user asked to delete. Destructive, so the panel confirms in-place
 * before calling `grain_space_delete_note`. `None` on every other turn.
 */
confirm_delete: AgentSource | null }
/**
 * One evidence source behind a Grain Recall answer (RECALL-PLAN §6.2). `title`
 * is the note's title (falling back to its summary); `saved_at` is a Unix-
 * millis timestamp for the chip's relative-age label. Empty for Assist.
 */
export type AgentSource = { note_id: string; title: string; saved_at: number }
/**
 * [GRAIN] How an [`AppMode`] is bound to the active target. A mode fires when the
 * foreground app (or, in a browser, the current site) matches. `Process` matches
 * the executable stem case-insensitively (e.g. `"Code"`, `"slack"`); `UrlHost`
 * matches the browser address-bar host by suffix (`"mail.google.com"` also
 * matches `"…mail.google.com"`), so users type a bare host, not a regex.
 */
export type AppMatch = { kind: "process"; value: string } | { kind: "url_host"; value: string }
/**
 * [GRAIN] A user-defined "mode": a specific post-processing prompt (HARD
 * formatting) applied ONLY when its `matcher` hits the active app/site. This is
 * the opt-in, per-target layer that rides on top of the always-on base prompt +
 * automatic soft context. The `prompt` is inline (self-contained) rather than a
 * reference into `post_process_prompts`, so a mode can be shared/exported whole.
 */
export type AppMode = { id: string; name: string; match: AppMatch; prompt: string; enabled?: boolean }
export type AppSettings = { bindings: Partial<{ [key in string]: ShortcutBinding }>; push_to_talk: boolean; audio_feedback: boolean; audio_feedback_volume?: number; sound_theme?: SoundTheme; 
/**
 * [GRAIN] Which panel is visible when the main window opens.
 */
default_panel?: DefaultPanel; start_hidden?: boolean; autostart_enabled?: boolean; update_checks_enabled?: boolean; selected_model?: string; 
/**
 * [GRAIN] Native ASR model id (separate registry from `selected_model`).
 * Empty = none selected. Never overload `selected_model`: Batch/Rolling and
 * Native ASR have different model topologies and lifecycles.
 */
selected_asr_model?: string; always_on_microphone?: boolean; selected_microphone?: string | null; clamshell_microphone?: string | null; selected_output_device?: string | null; translate_to_english?: boolean; selected_language?: string; overlay_position?: OverlayPosition; debug_mode?: boolean; log_level?: LogLevel; custom_words?: string[]; 
/**
 * [GRAIN] Voice snippets (Experimentations tab): trigger phrase → expansion.
 */
snippets?: Snippet[]; 
/**
 * [GRAIN] Voice actions (Experimentations tab): trigger phrase → open apps/sites.
 */
actions?: VoiceAction[]; model_unload_timeout?: ModelUnloadTimeout; word_correction_threshold?: number; history_limit?: number; recording_retention_period?: RecordingRetentionPeriod; paste_method?: PasteMethod; clipboard_handling?: ClipboardHandling; auto_submit?: boolean; auto_submit_key?: AutoSubmitKey; post_process_enabled?: boolean; post_process_provider_id?: string; post_process_providers?: PostProcessProvider[]; post_process_api_keys?: SecretMap; 
/**
 * [GRAIN] When true, post-processing routes among ENABLED post-process
 * providers (round-robin + per-provider daily quota + failover). When false
 * (default), the single `post_process_provider_id` is used — today's behavior.
 * Independent of STT rotation: each side has its OWN provider list.
 */
post_process_smart_rotation?: boolean; 
/**
 * [GRAIN] Local date (YYYY-MM-DD) the post-process daily quotas last reset on.
 */
post_process_quota_reset_date?: string; 
/**
 * [GRAIN] STT routing pool (local + remote OpenAI-compatible providers).
 */
stt_providers?: SttProvider[]; 
/**
 * [GRAIN] When true, transcription routes among enabled CLOUD providers
 * (round-robin + quota + failover); the LOCAL model is excluded. When false
 * (default), the local in-process model is used — never a surprise spike.
 */
stt_smart_rotation?: boolean; 
/**
 * [GRAIN] STT provider API keys, by pool-entry id. Split into grain.secrets.json.
 */
stt_api_keys?: SecretMap; 
/**
 * [GRAIN] Local date (YYYY-MM-DD) the STT daily quotas were last reset on.
 * When today differs, quotas roll back to 0 (checked lazily at routing time).
 */
stt_quota_reset_date?: string; post_process_models?: Partial<{ [key in string]: string }>; post_process_prompts?: LLMPrompt[]; post_process_selected_prompt_id?: string | null; mute_while_recording?: boolean; append_trailing_space?: boolean; app_language?: string; experimental_enabled?: boolean; lazy_stream_close?: boolean; keyboard_implementation?: KeyboardImplementation; show_tray_icon?: boolean; paste_delay_ms?: number; typing_tool?: TypingTool; external_script_path: string | null; custom_filler_words?: string[] | null; transcribe_accelerator?: TranscribeAcceleratorSetting; 
/**
 * transcribe-cpp compute-device *registry index* for explicit GPU picks
 * (`-1` = auto). NOTE: deliberately NOT aliased to the old
 * `whisper_gpu_device` — that was a transcribe-rs UI ordinal with different
 * semantics, so legacy values reset to auto instead of pointing at a
 * possibly different device.
 */
transcribe_gpu_device?: number; extra_recording_buffer_ms?: number; 
/**
 * [GRAIN] Voice conditioning before VAD + STT: 85 Hz high-pass (de-rumble)
 * + boost-only noise-gated AGC for quiet/laptop mics. On by default; helps
 * accuracy on low-volume input without touching already-loud audio.
 */
audio_conditioning?: boolean; 
/**
 * [GRAIN] Rolling live preview: show growing text in the Studio Window while
 * dictating in the rolling (real-time) mode. OFF by default and OFF is
 * truly zero-cost — the rolling worker takes exactly the same path it
 * always did (no events, no extra decode). ON adds a committed-text preview
 * after each chunk merge PLUS an efficient inter-chunk tail decode
 * (LocalAgreement-2) that costs extra compute, so it is strictly opt-in.
 */
rolling_live_preview?: boolean; 
/**
 * [GRAIN] Context awareness (post-processing only): when on, the backend
 * detects the foreground app/site right before LLM post-processing and layers
 * an automatic SOFT context line (tone/vocab, never restructuring) plus any
 * matching user [`AppMode`] (HARD formatting) on top of the selected base
 * prompt. OFF by default — zero behavior change until opted in, and it only
 * affects installs that also run post-processing.
 */
context_awareness_enabled?: boolean; 
/**
 * [GRAIN] User-defined per-app / per-site modes (HARD formatting). Empty by
 * default; only consulted when `context_awareness_enabled` is true.
 */
app_modes?: AppMode[]; 
/**
 * [GRAIN] Silent nearby-term hints: when on (and context awareness is on),
 * read UNIQUE non-dictionary tokens (proper nouns, code identifiers, library
 * names) from the focused field via UI Automation and pass them to the LLM as
 * an *additive, low-authority* bias — never the raw text, never persisted,
 * never surfaced in the UI. OFF by default because it reads the focused
 * field's content; password fields are always skipped.
 */
context_nearby_terms?: boolean; 
/**
 * [GRAIN] Auto-add to dictionary: when on, Grain briefly watches the field it
 * just pasted into (~10s) and, if you re-spell one of the pasted words the
 * same way across a couple of pastes, offers to add that spelling to your
 * dictionary (confirm by clicking the pill). OFF by default and **truly
 * zero-overhead when off** — no watcher is ever spawned. Only proper-noun /
 * identifier-shaped corrections are considered; common words are ignored.
 */
auto_dictionary_enabled?: boolean; 
/**
 * [GRAIN] Persisted learning counters for auto-add-to-dictionary (see
 * [`DictCandidate`]). Not user-facing; managed by the watcher.
 */
dictionary_candidates?: DictCandidate[]; 
/**
 * [GRAIN] Which Agent replies are auto-copied to the clipboard (off / first
 * reply only / every reply). Default `first` — the original behavior.
 */
agent_autocopy?: AgentAutocopy; 
/**
 * [GRAIN] Quick Agent: when on, submitting an instruction from the palette
 * runs the AI headlessly and pastes the reply straight at the cursor instead
 * of opening the reply panel. The pill then briefly offers "ask follow-up".
 */
agent_quick_enabled?: boolean; 
/**
 * [GRAIN] Agent context awareness: read the focused field at summon and pass
 * it to the AI as background (`unique` = high-signal terms only, `full` =
 * capped raw text). OFF by default.
 */
agent_context_mode?: AgentContextMode; 
/**
 * [GRAIN] "Scrap that" voice reset: when on, saying the phrase "scrap that"
 * mid-dictation discards everything spoken before it — the transcript starts
 * fresh from that point. Reuses the snippet matcher (no new engine), so OFF
 * is truly zero-overhead. In live-streaming modes the expanded Studio pill
 * resets and collapses back to the compact capsule until the next word.
 */
scrap_that_enabled?: boolean; 
/**
 * [GRAIN] Native agent input: when on (default), typing a printable key
 * while the input is listening immediately switches it to the expanded
 * typing card. When off, the input stays in voice mode and typing is
 * ignored until the user expands it explicitly (Tab / click).
 */
agent_input_type_to_expand?: boolean; 
/**
 * [GRAIN] Grain Space master gate. OFF by default and OFF is truly
 * zero-overhead: no shortcuts register, no directories are created, no
 * DB opens, no models load. Disabling never deletes on-disk data.
 */
grain_space_enabled?: boolean; 
/**
 * [GRAIN] Grain Space semantic search. OFF = fuzzy/FTS matching only and
 * the Candle embedding model must NEVER load into RAM. Turning it ON is
 * what triggers the opt-in BGE-small model download (the model is not
 * shipped with the app).
 */
grain_space_semantic?: boolean; 
/**
 * [GRAIN] When ON (default), reminders extracted from a captured note are
 * armed automatically; when OFF the note pane shows a manual "arm" button.
 */
grain_space_auto_reminders?: boolean; 
/**
 * [GRAIN] Voice-first retrieval behavior (Phase 5): open the results list
 * or answer directly with AI. Defaults to `List` — it needs no LLM.
 */
grain_space_retrieval_mode?: GrainSpaceRetrievalMode; 
/**
 * [GRAIN] Half-life (days) for time-decayed semantic ranking:
 * `S_final = S_semantic * exp(-ln2/half_life * age_days)`. Pinned notes
 * rank as if brand new (age 0).
 */
grain_space_decay_half_life_days?: number }
export type AudioDevice = { index: string; name: string; is_default: boolean }
export type AutoSubmitKey = "enter" | "ctrl_enter" | "cmd_enter"
export type AvailableAccelerators = { transcribe: string[]; gpu_devices: GpuDeviceOption[] }
export type BindingResponse = { success: boolean; binding: ShortcutBinding | null; error: string | null }
export type ClipboardHandling = "dont_modify" | "copy_to_clipboard"
export type CustomSounds = { start: boolean; stop: boolean }
export type DefaultPanel = "settings" | "quick_panel"
/**
 * [GRAIN] A one-shot snapshot of the current foreground app, for the "capture
 * focused app" button when creating a mode. Backend-side detection so the same
 * exe-stem normalization used at match time pre-fills the matcher exactly.
 */
export type DetectedApp = { 
/**
 * Executable stem (the value a `Process` mode matches on).
 */
exe: string; 
/**
 * Full, launchable executable path (for voice actions' app capture). Empty
 * when it couldn't be resolved.
 */
exe_path: string; 
/**
 * Human-facing name (window title, for display).
 */
name: string; 
/**
 * Browser address-bar host, when the foreground app is a browser and the
 * URL reader resolved it. `None` otherwise.
 */
url_host: string | null }
/**
 * [GRAIN] A learned-word candidate for auto-add-to-dictionary. When the user
 * repeatedly re-spells the same pasted word, `count` climbs; at the threshold it
 * is suggested (pill), and on accept it moves into `custom_words`. Persisted so
 * the count survives across sessions (the user rarely corrects the same term
 * twice in one sitting).
 */
export type DictCandidate = { 
/**
 * The corrected spelling as the user typed it (display + what gets added).
 */
word: string; 
/**
 * How many distinct paste-sessions this correction has been observed in.
 */
count: number }
export type EmbedModelStatus = "ready" | "downloading" | "absent"
export type EngineType = 
/**
 * Any GGML/GGUF model loaded through transcribe-cpp (Whisper, Parakeet,
 * Voxtral, Qwen3-ASR, Nemotron, …). The architecture is auto-detected from
 * the file, so this one variant covers the whole transcribe-cpp family.
 */
"TranscribeCpp" | "Parakeet" | "Moonshine" | "MoonshineStreaming" | "SenseVoice" | "GigaAM" | "Canary" | "Cohere"
export type GpuDeviceOption = { id: number; name: string; total_vram_mb: number }
/**
 * [GRAIN] Grain Space voice-first retrieval mode: `List` opens the overlay
 * with search results (works without any LLM); `AiQa` answers the spoken
 * question directly via the configured post-process provider (RAG).
 */
export type GrainSpaceRetrievalMode = "list" | "ai_qa"
export type HistoryEntry = { id: number; file_name: string; timestamp: number; saved: boolean; title: string; transcription_text: string; post_processed_text: string | null; post_process_prompt: string | null; post_process_requested: boolean }
export type HistoryUpdatePayload = { action: "added"; entry: HistoryEntry } | { action: "updated"; entry: HistoryEntry } | { action: "deleted"; id: number } | { action: "toggled"; id: number }
/**
 * Result of changing keyboard implementation
 */
export type ImplementationChangeResult = { success: boolean; 
/**
 * List of binding IDs that were reset to defaults due to incompatibility
 */
reset_bindings: string[] }
export type KeyboardImplementation = "tauri" | "handy_keys"
export type LLMPrompt = { id: string; name: string; prompt: string }
export type LogLevel = "trace" | "debug" | "info" | "warn" | "error"
export type ModelInfo = { id: string; name: string; description: string; filename: string; source: ModelSource; size_mb: number; is_downloaded: boolean; is_downloading: boolean; partial_size: number; is_directory: boolean; engine_type: EngineType; accuracy_score: number; speed_score: number; supports_translation: boolean; is_recommended: boolean; supported_languages: string[]; supports_language_selection: boolean; is_custom: boolean; supports_streaming: boolean; supports_language_detection: boolean }
export type ModelLoadStatus = { is_loaded: boolean; current_model: string | null }
/**
 * Where a model comes from and how Handy obtains it — the routing discriminant
 * for downloading and on-disk resolution.
 */
export type ModelSource = 
/**
 * Direct HTTP download from a URL (current blob.handy.computer hosting).
 */
{ Url: { url: string; 
/**
 * Expected SHA-256 for integrity verification; `None` skips it.
 */
sha256: string | null } } | 
/**
 * A file inside a Hugging Face Hub repo, fetched via hf-hub into the shared
 * HF cache (so other tools reuse it). The file within the repo is
 * [`ModelInfo::filename`].
 */
{ HuggingFace: { repo_id: string; revision: string } } | 
/**
 * Already present on disk — a user-provided custom model, or one discovered
 * in a shared cache. Nothing to download.
 */
"Local"
export type ModelUnloadTimeout = "never" | "immediately" | "min_2" | "min_5" | "min_10" | "min_15" | "hour_1" | "sec_15"
export type Note = { id: string; 
/**
 * 3-word AI title, or "" for raw (no-LLM) captures.
 */
title: string; 
/**
 * 1-sentence AI summary, or "" for raw captures.
 */
tldr: string; body: string; 
/**
 * Epoch ms (UTC). Date grouping happens in the UI, in local time.
 */
timestamp: number; todo_tags?: TodoTag[]; reminder_state?: ReminderState; is_pinned?: boolean }
export type OverlayPosition = "none" | "top" | "bottom" | 
/**
 * [GRAIN] Vertically centered — the Native ASR Studio Window's natural home
 * (a tall content box reads poorly hugging an edge); also selectable for
 * the small pill.
 */
"center"
export type PaginatedHistory = { entries: HistoryEntry[]; has_more: boolean }
export type PasteMethod = "ctrl_v" | "direct" | "none" | "shift_insert" | "ctrl_shift_v" | "external_script"
export type PermissionAccess = "allowed" | "denied" | "unknown"
export type PostProcessProvider = { id: string; label: string; base_url: string; allow_base_url_edit?: boolean; models_endpoint?: string | null; supports_structured_output?: boolean; 
/**
 * [GRAIN] Included in smart rotation when true. Defaults true so existing
 * configs (and the manual single-provider path) behave exactly as before.
 */
enabled?: boolean; 
/**
 * [GRAIN] Daily request cap for rotation; `None` = unlimited.
 */
quota_limit?: number | null; quota_used_today?: number }
/**
 * A read-only view of the post-process pool. API keys are NEVER returned — only
 * the set of provider ids that currently have a key stored, plus the per-provider
 * model map (model names are not secret).
 */
export type PpPoolView = { smart_rotation: boolean; providers: PostProcessProvider[]; selected_provider_id: string; providers_with_keys: string[]; models: Partial<{ [key in string]: string }> }
export type RecordingRetentionPeriod = "never" | "preserve_limit" | "days_3" | "weeks_2" | "months_3"
export type ReminderState = { status: ReminderStatus; 
/**
 * Epoch ms; `None` unless `status` is `Armed`/`Fired`.
 */
fire_at: number | null }
export type ReminderStatus = 
/**
 * No reminder on this note.
 */
"none" | 
/**
 * Extracted/suggested but not armed (auto-reminders off).
 */
"pending" | 
/**
 * Scheduled to fire at `fire_at`.
 */
"armed" | 
/**
 * Fired; kept for the settings-tab reminders list.
 */
"fired" | 
/**
 * User dismissed/completed it.
 */
"dismissed"
/**
 * Map of provider id → API key. Persisted to a SEPARATE credential file by
 * [`crate::context`], never inline in the main settings JSON. `Debug` redacts.
 */
export type SecretMap = Partial<{ [key in string]: string }>
export type ShortcutBinding = { id: string; name: string; description: string; default_binding: string; current_binding: string }
/**
 * [GRAIN] A voice snippet: when the (normalized) trigger phrase appears in a
 * final transcript, it is replaced by the expansion text verbatim. Matching is
 * case/punctuation tolerant so rolling-window chunk artifacts ("Grain, GitHub
 * repo.") still expand.
 */
export type Snippet = { id: string; trigger: string; replacement: string; enabled?: boolean }
export type SoundTheme = "marimba" | "pop" | "custom"
/**
 * Live transcription snapshot emitted to the overlay during a streaming run.
 * `committed` is the append-only, flicker-free prefix; `tentative` is the
 * volatile suffix the model may still rewrite.
 */
export type StreamTextEvent = { committed: string; tentative: string }
/**
 * A read-only view of the STT pool. API keys are NEVER returned — only the set
 * of provider ids that currently have a key stored.
 */
export type SttPoolView = { smart_rotation: boolean; providers: SttProvider[]; providers_with_keys: string[] }
/**
 * [GRAIN] One entry in the STT routing pool. Each entry carries its OWN key
 * (stored separately in `stt_api_keys` by `id`), so two entries with the same
 * `base_url` = two keys for one provider. Mirrors `provider_router::ProviderConfig`
 * plus the fields the HTTP client needs (`kind`, `model`).
 */
export type SttProvider = { id: string; name: string; kind: SttProviderKind; 
/**
 * Ignored for `Local`.
 */
base_url?: string; 
/**
 * Model/engine name sent to the provider (ignored for `Local`).
 */
model?: string; enabled?: boolean; 
/**
 * Daily request cap; `None` = unlimited.
 */
quota_limit?: number | null; quota_used_today?: number }
/**
 * [GRAIN] Which transcription backend an STT pool entry talks to. `Local` is the
 * in-process transcribe-rs model; the rest are HTTP adapters (see `stt_client`).
 */
export type SttProviderKind = 
/**
 * The in-process Parakeet/Whisper model (no network). Exactly one is implicit.
 */
"local" | 
/**
 * Generic OpenAI-compatible `/v1/audio/transcriptions`.
 */
"openai" | "deepgram" | "assemblyai"
export type TodoTag = { text: string; done: boolean }
/**
 * Compute preference for transcribe-cpp (whisper-family GGUF) model loads.
 * Renamed from `WhisperAcceleratorSetting` when the batch path moved from
 * transcribe-rs whisper.cpp onto transcribe-cpp (upstream parity); the stored
 * values (`auto`/`cpu`/`gpu`) are unchanged, so old JSON deserializes via the
 * field-level `alias` on [`AppSettings::transcribe_accelerator`].
 */
export type TranscribeAcceleratorSetting = "auto" | "cpu" | "gpu"
export type TypingTool = "auto" | "wtype" | "kwtype" | "dotool" | "ydotool" | "xdotool"
/**
 * [GRAIN] A voice ACTION (Experimentations tab): when the (normalized) trigger
 * phrase is spoken, every `target` is opened and the trigger is stripped from
 * the pasted text. One action can open several apps + sites at once — a
 * "workflow" (e.g. "start coding" opens the editor, terminal, and two docs).
 * Matching reuses the snippet matcher, so it is case/punctuation tolerant and
 * survives rolling-window chunk artifacts. No AI, no network — a local launch.
 */
export type VoiceAction = { id: string; trigger: string; targets: ActionTarget[]; enabled?: boolean }
export type WindowsMicrophonePermissionStatus = { supported: boolean; overall_access: PermissionAccess; device_access: PermissionAccess; app_access: PermissionAccess; desktop_app_access: PermissionAccess }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
